### PR TITLE
`ConfigControls`, copy & paste support and context based context menu

### LINKED ISSUE #562: Widget `ConfigControls`
We already have the types for our abstraction layer for widget-specific configuration. Especially for the current development in the Daedalus 2 project, it would be great if we could add its implementation soon. 😃 

For the types, please see https://github.com/wuespace/telestion-client/blob/28a85e8359b4f127a1bd956c9a14184d36e59034/packages/telestion-client-types/src/widgets/widget.ts#L194.

Within the documentation of the types, there's even a small example of what we thought about how they should be used:

```ts
function ConfigControls({
  currentProps, onUpdate
}: ConfigControlsProps): ReactNode {
  // local state to not "flood" global store with changes (performance)
  const [value, setValue] = useState(currentProps.value);
  return (
    <div>
      <input type="text" value={value} onChange={event => setValue(event.target.value)} />
      <button onClick={() => onUpdate({ value })} />
    </div>
  );
}
```

I genuinely believe that this is the right amount of abstraction for implementing widget-specific configuration since it allows widget developers to easily add dynamically configurable properties to their widgets without sacrificing the depth of configuration options (after all, any `JSONSerializable` configuration can be passed to `onUpdate`).

### PR DESCRIPTION
**Pull request by fussel178**
### Summary 

Implement the widget configuration mode with copy & paste and context menu support.

#### types

- Add a unique identifier to a widget definition
- Remove title as required widget configuration and therefore the `GlobalRendererProps` because it is no longer needed. A widget must now export a version.
- Add context menu types (MenuItem and Section)

#### common

- The widget renderer now uses the widget.id to identify the currently rendered widgets
- Implement the widget configuration mode which renders the exported `ConfigControls` for every widget.
- Implement the copy and paste feature which allows the transfer of configurations between widgets.
- Update eventbus debug widget to be compatible with the `Widget` definition.
- Implement ContextMenuProvider and `ContextMenuWrapper` that allows the usage of custom context menu in the application (see documentation for more information)
- Implement ContextMenu component which renders the registered menu items on a context event
- Insert the ContextMenuProvider into the `CommonWrapper` component to provide context menu support by default for projects using the `CommonWrapper` component
- Register a context menu item to configure the widget on a context event
- Add a reset configuration menu entry to the avatar menu
- Add tooltips to copy and paste actions in widget configuration
- Fix some styling issues related to widget configuration and context menu

#### Breaking Changes

- A widget definition for a dashboard configuration now requires a unique identifier.
- The `GlobalRendererProps` type is removed. An exported widget now requires a `version` property. The `title` property is removed from the `WidgetDefinition` type.

### Related links 

- Closes #562 

### CLA

- [x] I have signed the individual contributor's license agreement **and sent** it to the board of the WüSpace e. V. organization.

# :cheese:

---
This change is [Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681)

### CODE REVIEW

**Review by pklaschka — CHANGES_REQUESTED** [review]
> Reviewed 66 of 66 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681)* status: all files reviewed, 7 unresolved discussions (waiting on @fussel178 and @jantischhoefer)

___
*[packages/telestion-client-common/src/components/context-menu/wrappers/context-menu-wrapper.tsx, line 31 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcpos4u0lOXaSCind6u:-Mcpos4u0lOXaSCind6v:boietzu) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/components/context-menu/wrappers/context-menu-wrapper.tsx#L31)):*
> ```
>  An optional title the section in the context menu.
> ```
This should probably be "of the section" ;)
___
*[packages/telestion-client-common/src/components/header/account-controls/avatar-menu.tsx, line 70 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcppqak9JB7cIEIGQep:-McppqalBmU6QKDH0GAr:b-s5mp1w) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/components/header/account-controls/avatar-menu.tsx#L70)):*
> ```XML
> 				onStatusClick();
> 			} else if (key === 'reset') {
> 				localStorage.clear();
> ```

Could we maybe wrap this in a "confirmation" box? It doesn't have to be fancy (a simple `window.confirm` will probably do the trick). Just so that a miss-click doesn't delete the whole configuration :wink: 
___
*[packages/telestion-client-common/src/components/pages/dashboard-page/dashboard/widget-renderer/config-renderer.tsx, line 56 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-McprLrR3A_RyGjEmfxs:-McprLrR3A_RyGjEmfxt:b8vtb9t) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/components/pages/dashboard-page/dashboard/widget-renderer/config-renderer.tsx#L56)):*
> ```
>  * It implements the copy and paste for widget properties.
> ```
=> "[...] the copy and paste functionality for [...]"
___
*[packages/telestion-client-common/src/media/rocket.png, line 0 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcpu5G33ZhpOeDZfive:-Mcpu5G33ZhpOeDZfivf:b-arxmfz) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/media/rocket.png#L0)):*
Where does this image come from? Have you designed it? If not: How is the licensing?
___
*[packages/telestion-client-types/src/context-menu.ts, line 12 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-McpuoxN6OQpNynjFIiV:-McpuoxN6OQpNynjFIiW:b-g6ey3t) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-types/src/context-menu.ts#L12)):*
> ```
>  * that are triggered if the user presses the context menu entry.
> ```
=> "that is triggered [...]"
___
*[packages/telestion-client-types/src/context-menu.ts, line 42 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcpv2w95QyKhgaU84as:-Mcpv2w95QyKhgaU84at:b-481scz) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-types/src/context-menu.ts#L42)):*
> ```XML
> 	/**
> 	 * An optional icon that are rendered within the menu entry
> 	 * beside the {@link MenuItem.title}.
> ```

Minor. Could we please add a small sentence like: "No icon gets displayed if `icon === undefined`" or something like that?
___
*[packages/telestion-client-types/src/context-menu.ts, line 47 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-McpvGDm7jLC2AH8KE7u:-McpvGDm7jLC2AH8KE7v:byuh9r8) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-types/src/context-menu.ts#L47)):*
> ```
> 	 * The action that are triggered if the users presses the menu entry.
> ```
=> "[...] that gets triggered if the user presses [...]"

**Review by fussel178 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681)* status: 62 of 66 files reviewed, 6 unresolved discussions (waiting on @jantischhoefer and @pklaschka)

___
*[packages/telestion-client-common/src/components/context-menu/wrappers/context-menu-wrapper.tsx, line 31 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcpos4u0lOXaSCind6u:-McqI67y5icZd2SDoWXQ:b-896fix) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/components/context-menu/wrappers/context-menu-wrapper.tsx#L31)):*
<details><summary><i>Previously, pklaschka (Pablo Klaschka) wrote…</i></summary><blockquote>

> ```
>  An optional title the section in the context menu.
> ```
This should probably be "of the section" ;)
</blockquote></details>

Done.
___
*[packages/telestion-client-common/src/components/header/account-controls/avatar-menu.tsx, line 70 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcppqak9JB7cIEIGQep:-McqIBe5-kJ-G5hmaDm6:bny2xoi) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/components/header/account-controls/avatar-menu.tsx#L70)):*
<details><summary><i>Previously, pklaschka (Pablo Klaschka) wrote…</i></summary><blockquote>

Could we maybe wrap this in a "confirmation" box? It doesn't have to be fancy (a simple `window.confirm` will probably do the trick). Just so that a miss-click doesn't delete the whole configuration :wink: 
</blockquote></details>

Of course!
___
*[packages/telestion-client-common/src/components/pages/dashboard-page/dashboard/widget-renderer/config-renderer.tsx, line 56 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-McprLrR3A_RyGjEmfxs:-McqJ-hLB72C72D79Trp:b-896fix) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/components/pages/dashboard-page/dashboard/widget-renderer/config-renderer.tsx#L56)):*
<details><summary><i>Previously, pklaschka (Pablo Klaschka) wrote…</i></summary><blockquote>

> ```
>  * It implements the copy and paste for widget properties.
> ```
=> "[...] the copy and paste functionality for [...]"
</blockquote></details>

Done.
___
*[packages/telestion-client-common/src/media/rocket.png, line  at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcpu5G33ZhpOeDZfive:-McqJ33y0860QsZ8QG3Q:bvrm2x6) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/media/rocket.png#L)):*
<details><summary><i>Previously, pklaschka (Pablo Klaschka) wrote…</i></summary><blockquote>

Where does this image come from? Have you designed it? If not: How is the licensing?
</blockquote></details>

Well, good question.
It's from here:
https://www.iconfinder.com/icons/286673/rocket_icon

And I think, we need to link his webpage:
https://therealjerrylow.com/

Any ideas where or in which corner on the overlay?
___
*[packages/telestion-client-types/src/context-menu.ts, line 12 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-McpuoxN6OQpNynjFIiV:-McqJsse98UGKBZK2LsM:b-896fix) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-types/src/context-menu.ts#L12)):*
<details><summary><i>Previously, pklaschka (Pablo Klaschka) wrote…</i></summary><blockquote>

> ```
>  * that are triggered if the user presses the context menu entry.
> ```
=> "that is triggered [...]"
</blockquote></details>

Done.
___
*[packages/telestion-client-types/src/context-menu.ts, line 47 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-McpvGDm7jLC2AH8KE7u:-McqKBqmBpd3QhUBPyBx:b-896fix) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-types/src/context-menu.ts#L47)):*
<details><summary><i>Previously, pklaschka (Pablo Klaschka) wrote…</i></summary><blockquote>

> ```
> 	 * The action that are triggered if the users presses the menu entry.
> ```
=> "[...] that gets triggered if the user presses [...]"
</blockquote></details>

Done.

**Review by fussel178 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681)* status: 62 of 66 files reviewed, 6 unresolved discussions (waiting on @jantischhoefer and @pklaschka)

___
*[packages/telestion-client-common/src/components/header/account-controls/avatar-menu.tsx, line 70 at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcppqak9JB7cIEIGQep:-McqMe-a-hLU9X7-6I5n:b-896fix) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/components/header/account-controls/avatar-menu.tsx#L70)):*
<details><summary><i>Previously, fussel178 (Ludwig Richter) wrote…</i></summary><blockquote>

Of course!
</blockquote></details>

Done.

**Review by pklaschka — CHANGES_REQUESTED** [review]
First of all: Thank you for the changes. I've left some more feedback regarding the icon licensing issue, but other than that, it LGTM!

> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681#-:-McqNkYg3GN3QxAzxx7e:b4qumo2)* status: 65 of 66 files reviewed, 1 unresolved discussion (waiting on @fussel178, @jantischhoefer, and @pklaschka)

___
*[packages/telestion-client-common/src/media/rocket.png, line  at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcpu5G33ZhpOeDZfive:-McqMm9y9gDhTrohawi4:b-p9hbpu) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/media/rocket.png#L)):*
Alright. Could we, in this case, please add some `rocket.png.txt` file next to the image file that also includes this license notice. Otherwise, this might get mixed up with the "outer" MIT license... :thinking: 

> Any ideas where or in which corner on the overlay?

Wherever it fits best... I'm not sure if it was here or in the other repo that there also is a small text in the corner. If it was here, let's just add it as another line... otherwise ... I'd suggest adding it in the lower right-hand corner :wink:

**Review by pklaschka — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681)* status: all files reviewed, 1 unresolved discussion (waiting on @fussel178 and @jantischhoefer)

**Review by fussel178 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681)* status: all files reviewed, 1 unresolved discussion (waiting on @jantischhoefer and @pklaschka)

___
*[packages/telestion-client-common/src/media/rocket.png, line  at r1](https://reviewable.io/reviews/wuespace/telestion-client/681#-Mcpu5G33ZhpOeDZfive:-McqUKtq4K5W42uCZ7PT:b-896fix) ([raw file](https://github.com/wuespace/telestion-client/blob/fd94075c5f0ef22d189619b722d6cd1d385e03e2/packages/telestion-client-common/src/media/rocket.png#L)):*
<details><summary><i>Previously, pklaschka (Pablo Klaschka) wrote…</i></summary><blockquote>

Alright. Could we, in this case, please add some `rocket.png.txt` file next to the image file that also includes this license notice. Otherwise, this might get mixed up with the "outer" MIT license... :thinking: 

> Any ideas where or in which corner on the overlay?

Wherever it fits best... I'm not sure if it was here or in the other repo that there also is a small text in the corner. If it was here, let's just add it as another line... otherwise ... I'd suggest adding it in the lower right-hand corner :wink: 
</blockquote></details>

Done.

**Review by pklaschka — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681#-:-McqVjXN2ezT6Nu1utoj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jantischhoefer)

**Review by fussel178 — COMMENTED** [review]
:grin: 

> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681#-:-McqVuVu5pW4aZmrtMlH:be0530r)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jantischhoefer)

**Review by pklaschka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-client/681)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jantischhoefer)

**Pull request merged**
